### ISSUE TITLE
Stories single page: optimize header on small screens

### ISSUE THREAD

**Issue by ricardoduplos** [NASA-IMPACT/covid-dashboard#458]
## Tasks

- [x] Truncate story title
- [x] Truncate chapter title
- [x] Hide chapter count

<img width="1298" alt="Screen Shot 2020-11-19 at 15 17 50" src="https://user-images.githubusercontent.com/1016701/99685437-7dce9780-2a7a-11eb-8b17-f12a599280ab.png">

**Comment by olafveerman** [comment]
Done. Fixed in branch.
